# TODO -
# There's a reasonably high dependence on the artifacts and the docker images that generate them.
# in the future, we may run into a problem where the jetson is upgraded and we need to change
# this file. The future approach would be:
# 1. Generate a pair of docker images for the python wheels and upgrade images. One for arm and one for x86.
# 2. Use variables to help define the build environment and to tag the correct docker image. For example:
# x86_64: &x86_64
#  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pybind11-${BASE_IMAGE_SUFFIX}
#
# .arm64: &arm64
#  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pyjerrycan-arm-${BASE_IMAGE_SUFFIX}
#  tags:
#    - arm64
#
#.py3_8: &py3_8
#  variables:
#    PY_VERSION: "3.8"
#    BASE_IMAGE_SUFFIX: "py38"
#
#.py3_12: &py3_12
#  variables:
#    PY_VERSION: "3.12"
#    BASE_IMAGE_SUFFIX: "py312"
#
#build_pyjerrycan_arm_py3_8:
#  <<: *build_libjerrycan
#  <<: *arm64
#  <<: *py3_8
#
#build_pyjerrycan_x86_64_py3_12:
#  <<: *build_libjerrycan
#  <<: *x86_64
#  <<: *py3_12

stages:
  - check
  - build
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  FF_SCRIPT_SECTIONS: "true"
  FIRMWARE_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/module_firmware/${CI_COMMIT_TAG}"
  HOST_TOOLS_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/host_tools/${CI_COMMIT_TAG}"
  PYPI_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"

# Job that is run on merge requests
check_formatting:
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/code-format
  interruptible: true
  stage: check
  variables:
    ENFORCE_FORMAT_DIR: 'firmware'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - $ENFORCE_FORMAT_DIR/**/*
        - docker/**/*
  script:
    - git fetch
    - git-clang-format -v --commit origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -q --diff -- $ENFORCE_FORMAT_DIR

.build_firmware_template: &build_firmware_template
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/zephyr-sdk
  stage: build
  cache:
    key: deps-cache
    paths:
      - deps
  artifacts:
    paths:
      - firmware/*.hex
      - firmware/*.bin
  rules:
    - changes:
        - firmware/**/*
        - docker/**/*
  script:
    - cd firmware
    - west init -l
    - west update
    - cd ${MODULE}
    - west build -p --sysbuild -b ${BOARD}
    - GIT_DESCRIBE=$(git describe --tags --always --dirty)
    - cp build/${MODULE}/zephyr/zephyr.signed.hex ../${MODULE}_fw_${GIT_DESCRIBE}.hex
    - cp build/${MODULE}/zephyr/zephyr.signed.bin ../${MODULE}_fw_${GIT_DESCRIBE}.bin
    - cp build/mcuboot/zephyr/zephyr.hex ../${MODULE}_${GIT_DESCRIBE}_bootloader.hex
    - cp build/mcuboot/zephyr/zephyr.bin ../${MODULE}_${GIT_DESCRIBE}_bootloader.bin

build_pellet_firmware:
  <<: *build_firmware_template
  variables:
    MODULE: pellet_module
    BOARD: cerebellumlab_pellet_module

build_pellet_firmware_nucleo_g474re:
  <<: *build_firmware_template
  variables:
    MODULE: pellet_module
    BOARD: nucleo_g474re
  script:
    - cd firmware
    - west init -l
    - west update
    - cd ${MODULE}
    - west build -p --sysbuild -b ${BOARD}
    - GIT_DESCRIBE=$(git describe --tags --always --dirty)
    - cp build/${MODULE}/zephyr/zephyr.hex ../${MODULE}_${BOARD}_fw_${GIT_DESCRIBE}.hex
    - cp build/${MODULE}/zephyr/zephyr.bin ../${MODULE}_${BOARD}_fw_${GIT_DESCRIBE}.bin

build_magnet_firmware:
  <<: *build_firmware_template
  variables:
    MODULE: magnet_module
    BOARD: cerebellumlab_magnet_module

# Build pyjerrycan/libjerrycan
.build_libjerrycan: &build_libjerrycan
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pybind11
  stage: build
  rules:
    - changes:
        - software/libjerrycan/**/*
        - docker/pybind11/**/*
  script:
    - cd software/libjerrycan
    - pip3 wheel . -w ${CI_PROJECT_DIR}/wheels
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/wheels/pyjerrycan*.whl

# Build architecture specific wheels for pyjerrycan
build_pyjerrycan_x86_64:
  <<: *build_libjerrycan

build_pyjerrycan_arm64:
  <<: *build_libjerrycan
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pyjerrycan-arm
  tags:
    - arm64

# Build jerrycan_updater
.build_jerrycan_updater: &build_jerrycan_updater
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pybind11
  stage: build
  rules:
    - changes:
        - software/jerrycan_updater/**/*
        - docker/pybind11/**/*
  script:
    - GIT_DESCRIBE=$(git describe --tags --always --dirty)
    - cmake -B build -DCMAKE_INSTALL_PREFIX:PATH=../tmp -GNinja
    - ninja -C build jerrycan_updater
    - mkdir host_tools
    - cp build/software/jerrycan_updater/jerrycan_updater host_tools/jerrycan_updater_${GIT_DESCRIBE}_${PLATFORM}
  artifacts:
    paths:
      - host_tools/jerrycan_updater_*

# Build architecture specific versions of jerrycan_updater
build_jerrycan_updater_x86_64:
  <<: *build_jerrycan_updater
  variables:
    PLATFORM: x86_64

build_jerrycan_updater_arm64:
  <<: *build_jerrycan_updater
  variables:
    PLATFORM: arm64
  tags:
    - arm64

# Build WhiskerWire
build_whiskerwire:
  image: registry.gitlab.leaflabs.com/cuanschutz/autotrainer/pybind11
  stage: build
  rules:
    - changes:
        - software/whiskerwire/**/*
        - docker/pybind11/**/*
  script:
    - cd software/whiskerwire
    - pip3 wheel ../libjerrycan . -w ${CI_PROJECT_DIR}/wheels
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/wheels/whiskerwire*.whl

# Generate diffs for PCB projects
.generate_hardware_diffs_template: &generate_hardware_diffs_template
  image:
    name: leoheck/kiri:latest
    docker:
      user: root
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - $PROJECT_DIR/**/*
  artifacts:
    paths:
      - $PROJECT_DIR/.kiri
  before_script:
    - export PATH=$PATH:/home/kiri/.local/share/kiri/bin/:/home/kiri/.local/share/kiri/submodules/KiCad-Diff/bin:/home/kiri/bin
    - export TERM=xterm
    - apt update && apt install -y curl
    - export
  script:
    - kiri --no-server -o $(git rev-parse --short $CI_MERGE_REQUEST_DIFF_BASE_SHA) $PROJECT_DIR/$PROJECT_FILE
    - >-
      curl --location \
           --request POST "https://gitlab.leaflabs.com/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" \
           --header "PRIVATE-TOKEN: $PROJECT_ACCESS_TOKEN" \
           --header "Content-Type: application/json" \
           --data-raw "{ \"body\": \"Board Diff for [$PROJECT_DIR - $CI_PIPELINE_ID](https://$CI_PROJECT_NAMESPACE.pages.leaflabs.com/-/autotrainer/-/jobs/$CI_JOB_ID/artifacts/$PROJECT_DIR/.kiri/web/index.html)\" }"

generate_pellet_diffs:
  <<: *generate_hardware_diffs_template
  variables:
    PROJECT_DIR: hardware/pellet_module
    PROJECT_FILE: pellet.kicad_pro

generate_magnet_diffs:
  <<: *generate_hardware_diffs_template
  variables:
    PROJECT_DIR: hardware/magnet_module
    PROJECT_FILE: magnet.kicad_pro

generate_jetson_diffs:
  <<: *generate_hardware_diffs_template
  variables:
    PROJECT_DIR: hardware/jetson_breakout
    PROJECT_FILE: jetson_breakout.kicad_pro

# Upload host tools to the package registry
upload_host_tools:
  stage: release
  image: curlimages/curl:latest
  needs:
    - job: build_jerrycan_updater_x86_64
      artifacts: true
    - job: build_jerrycan_updater_arm64
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - >
      for file in host_tools/*; do
        if [ -f "$file" ]; then
          filename=$(basename "$file")
          echo "$file"
          echo "$filename"
          curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               --upload-file "$file" \
               "${HOST_TOOLS_PACKAGE_REGISTRY_URL}/$filename"
          echo "Uploaded: $filename"
        fi
      done

# Upload the module firmware binaries and host tools to the package registry
upload_fw_job:
  stage: release
  image: curlimages/curl:latest
  needs:
    - job: build_pellet_firmware
      artifacts: true
    - job: build_magnet_firmware
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "${PACKAGE_REGISTRY_URL}"
    - >
      for file in firmware/*.bin; do
        if [ -f "$file" ]; then
          filename=$(basename "$file")
          echo "$file"
          echo "$filename"
          curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               --upload-file "$file" \
               "${FIRMWARE_PACKAGE_REGISTRY_URL}/$filename"
          echo "Uploaded: $filename"
        fi
      done

# Upload python packages to the package registry
upload_py_job:
  stage: release
  image: python
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build_pyjerrycan_x86_64
      artifacts: true
    - job: build_pyjerrycan_arm64
      artifacts: true
    - job: build_whiskerwire
      artifacts: true
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  script:
    - pip install twine
    - python -m twine upload --repository-url $PYPI_PACKAGE_REGISTRY_URL ${CI_PROJECT_DIR}/wheels/*

# Create a release package for the module firmware and python packages
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: upload_fw_job
    - job: upload_py_job
    - job: upload_host_tools
  script:
    - echo "Creating release package for $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "CI/CD Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Pellet Firmware"
          url: "${FIRMWARE_PACKAGE_REGISTRY_URL}/pellet_module_fw_${CI_COMMIT_TAG}.bin"
        - name: "Magnet Firmware"
          url: "${FIRMWARE_PACKAGE_REGISTRY_URL}/magnet_module_fw_${CI_COMMIT_TAG}.bin"
        - name: "JerryCAN Updater (x86_64)"
          url: "${HOST_TOOLS_PACKAGE_REGISTRY_URL}/jerrycan_updater_${CI_COMMIT_TAG}_x86_64"
        - name: "JerryCAN Updater (arm64)"
          url: "${HOST_TOOLS_PACKAGE_REGISTRY_URL}/jerrycan_updater_${CI_COMMIT_TAG}_arm64"
