CONFIG_LOG=y
CONFIG_SHELL=y
CONFIG_CONSOLE=y

CONFIG_PM=n
CONFIG_PM_DEVICE=n

# Flash driver to store firmware image
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_STREAM_FLASH=y

CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y
CONFIG_INPUT_MODE_SYNCHRONOUS=y
CONFIG_INPUT_EVENT_DUMP=n

CONFIG_LIB_MOTOR_MOTION=y

CONFIG_LIB_JERRYCAN=n
CONFIG_LIB_JERRYCAN_RGB_LED=n
CONFIG_LIB_JERRYCAN_DOOR_SENSOR=n

CONFIG_DEBUG=y
CONFIG_DMA_LOG_LEVEL_DBG=n

# This is useful for debugging, but not recommended for production
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30
# CONFIG_THREAD_NAME=y

CONFIG_SETTINGS=y
CONFIG_SETTINGS_SHELL=y

CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y

CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y


CONFIG_LIB_JERRYCAN=y
CONFIG_LIB_JERRYCAN_DOOR_SENSOR=y
CONFIG_LIB_JERRYCAN_RGB_LED=y

CONFIG_LIB_MOTOR_MOTION_SHELL=y
CONFIG_ADI_TMC2209_SHELL=y

# Run-Time Priorities

# Highest priority is managing the servos and motors
CONFIG_LIB_MOTOR_MOTION_WORK_QUEUE_PRIORITY=-3
# Then the CANbus I/O (jerrycan_run is called within the context of main())
CONFIG_MAIN_THREAD_PRIORITY=-2
# Background writes should have lowest priority
CONFIG_LIB_MOTOR_MOTION_SETTINGS_WORK_QUEUE_PRIORITY=99

# Stack Sizes

CONFIG_LIB_MOTOR_MOTION_WORK_QUEUE_STACK_SIZE=1024
CONFIG_LIB_MOTOR_MOTION_SETTINGS_WORK_QUEUE_STACK_SIZE=1024
